type: 'byol'
project_name: 'BYOL_Debug'
dataset: 'rgz' # ['imagenette', 'rgz', 'gzmnist', 'gz2', 'stl10', 'cifar10']
seed: 0

dataloading:
  num_workers: 8  # often overriden
  prefetch_factor: 30
  persistent_workers: False  # torch default is False
  pin_memory: True
  val_batch_size: 250 # validation batch size

evaluation:
  finetune: True
  knn_eval: False
  linear_eval: True
  n_eval_epochs: 1
  checkpoint_mode: 'last'
  early_stopping: False
  n_iterations: 1
  topk: 5
  check_val_every_n_epoch: 20

finetune:
  seed: 0
  n_layers: 0 
  lr_decay: 0.75
  n_epochs: 200
  batch_size: 100

compute: 'slurm'
precision: 32 # [16, 32, 'bf16'], often overriden
profiler: 'none'

trainer:
  accelerator: 'gpu' # set to 1 to disable multi gpu training
  devices: 1
  num_nodes: 1
  strategy: 'auto' 
  fast_dev_run: False # debugging mode
  precision: 32 # [16, 32, 'bf16'], often overriden
  deterministic: True
